# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # Adjust branch name as needed

resources:
- repo: self  # Refers to the current repository

variables:
  imageName: '$(Build.Repository.Name)'  # Use repository name as the image name
  tag: '$(Build.BuildId)'  # Tag the image with Build ID

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker Image Job'
    pool:
      name : 'default'  # You can use a self-hosted agent if desired
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '$frontend/Dockerfile'  # Path to the Dockerfile
        tags: |
          $(frontend):$(v1)  # Tag the image with the repository name and Build ID
